### ISSUE TITLE
Echo Trainer: Abbreviations should show up quicker: before next abbrev. starts

### ISSUE THREAD

**Issue by quarksteilchen** [cdaller/morserino32-trainer#4]
In Echo Trainer (beta) mode, there is this feature which looks up and displays common CW abbreviations.

Currently, the meaning/description is shown only after some time after reception. It seems only when the next abbreviation is transmitted by the morserino the lookup of the description is done.

It might be a good idea to already load it after the "OK" is received.

**Comment by cdaller** [comment]
yes! Already implemented it that way now (was different before)
