### ISSUE TITLE
Collection of CW abbreviations

### ISSUE THREAD

**Issue by quarksteilchen** [cdaller/morserino32-trainer#5]
You can use this list: https://docs.google.com/spreadsheets/d/1ts38a33wrM31sx71aBhX_CTw-HkMzpenzmzQGZsL_44/edit?usp=sharing
(i added the "code" header for copy/pasting the content into your source code)

It was collected from the morserinos' source code ([abbrev.h](https://github.com/oe1wkl/Morserino-32/blob/master/Software/src/Version%204/abbrev.h )) in comparison with OE6RDD CW Schule Graz' documentation.

**Comment by cdaller** [comment]
thanks, already included your list and more abbreviations from wikipedia
